apiVersion: v1
kind: ReplicationController
metadata:
  name: esp-rc
spec:
  replicas: 1
  selector:
    app: esp
  template:
    metadata:
      labels:
        app: esp 
    spec:
      containers:
        - name: esp
          image: hpccsystems/platform-ce:latest
          ports:
            - containerPort: 8010
          securityContext:
            privileged: true
          command:
            - /tmp/start_hpcc.sh
